version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "fix(deps)"
    open-pull-requests-limit: 15

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "fix(deps)"
    open-pull-requests-limit: 15

  - package-ecosystem: "nuget"
    directory: "/backend"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "fix(deps)"
    open-pull-requests-limit: 15