services:
  nzbdav:
    restart: unless-stopped 
    container_name: nzbdav 
    image: ghcr.io/nzbdav-dev/nzbdav:pre-alpha
    hostname: nzbdav 
    environment: 
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - /opt/nzbdav/config=/config
      - LOG_LEVEL=INFO
    networks: 
      - saltbox
    labels:
      com.github.saltbox.saltbox_managed: true 
      traefik.enable: true 
      autoheal: true
      autoheal.stop.timeout: 10
      traefik.http.routers.nzbdav-http.entrypoints: web 
      traefik.http.routers.nzbdav-http.middlewares: globalHeaders@file,redirect-to-https@docker,robotHeaders@file,cloudflarewarp@docker,authelia@docker
      traefik.http.routers.nzbdav-http.rule: Host(`nzbdav.mewtwomedia.net`)
      traefik.http.routers.nzbdav-http.service: nzbdav 
      traefik.http.routers.nzbdav.entrypoints: websecure 
      traefik.http.routers.nzbdav.middlewares: globalHeaders@file,secureHeaders@file,robotHeaders@file,cloudflarewarp@docker,authelia@docker 
      traefik.http.routers.nzbdav.rule: Host(`nzbdav.mewtwomedia.net`) 
      traefik.http.routers.nzbdav.service: nzbdav 
      traefik.http.routers.nzbdav.tls.certresolver: cfdns 
      traefik.http.routers.nzbdav.tls.options: securetls@file 
      traefik.http.services.nzbdav.loadbalancer.server.port: 3000 
    volumes: 
      - /opt/nzbdav:/config
      - /etc/localtime:/etc/localtime:ro

  nzbdav-webdav:
    image: rclone/rclone:latest
    container_name: nzbdav-webdav
    restart: unless-stopped
    command: |
      mount nzbdav: /data
      --no-modtime
      --no-checksum
      --fast-list
      --allow-other
      --allow-non-empty
      --dir-cache-time=15s
      --links
      --uid=1000
      --gid=1000
      --async-read=true
      --vfs-fast-fingerprint
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - /mnt/remote/nzbdav:/data:rshared
      - ./rclone.conf:/config/rclone/rclone.conf:ro
    networks:
      - saltbox
    depends_on:
      - nzbdav

networks:
  saltbox:
    external: true
